os: linux
dist: bionic

language: shell

addons:
  apt:
    packages:
    - qtbase5-dev-tools

script:
 - chmod ugo+x themes.sh
 - /bin/bash ./themes.sh

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "test"
  - git config --local user.email "test@test.com"
  - export TRAVIS_TAG="continuous"
  - git tag -f $TRAVIS_TAG

deploy:
  provider: releases
  token: $GH_TOKEN
  file_glob: true
  file: deploy/*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
