os: linux
dist: bionic

language: shell

addons:
  apt:
    packages:
    - qtbase5-dev-tools

# script:
#  - # /usr/bin/rcc --version
#  - # python3 file.py

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "test"
  - git config --local user.email "test@test.com"
  - TRAVIS_TAG="continuous"
  - git tag -d $TRAVIS_TAG
  - git push --delete origin $TRAVIS_TAG
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  token: $GH_TOKEN
  file: "README.md"
  cleanup: false
  # on:
  #   tags: true
